model: "allenai/OLMo-2-0425-1B"
revision: null
factors_dir: "/workspace/hessian_output"
query_batch_size: 8
train_batch_size: 8
max_concurrent_runs: 1
max_length: 512
if_query_dir: "../if-query"
data_dir: "data"
